jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"sap/git/basic/GitBasicProject/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","sap/git/basic/GitBasicProject/model/models"],function(e,i,t){"use strict";return e.extend("sap.git.basic.GitBasicProject.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"sap/git/basic/GitBasicProject/controller/View1.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(i){"use strict";return i.extend("sap.git.basic.GitBasicProject.controller.View1",{onInit:function(){}})});
},
	"sap/git/basic/GitBasicProject/i18n/i18n.properties":'title=Title\nappTitle=GitBasicProject\nappDescription=App Description',
	"sap/git/basic/GitBasicProject/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"sap.git.basic.GitBasicProject","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"sap.git.basic.GitBasicProject.view.View1","type":"XML","async":true,"id":"View1"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"sap.git.basic.GitBasicProject.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"sap.git.basic.GitBasicProject.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":"RouteView1","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}}},"sap.platform.hcp":{"uri":"webapp","_version":"1.1.0"}}',
	"sap/git/basic/GitBasicProject/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"sap/git/basic/GitBasicProject/view/View1.view.xml":'<mvc:View controllerName="sap.git.basic.GitBasicProject.controller.View1" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content><Label text="Welcome to Git" width="100%" id="idWelcome" design="Bold"/></content></Page></pages></App></Shell></mvc:View>'
}});
